[2023-08-31T23:10:00.668+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509
[2023-08-31T23:10:00.669+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table'
[2023-08-31T23:10:00.710+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509
[2023-08-31T23:10:00.711+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table'
[2023-08-31T23:10:00.737+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.create_listings_raw_table manual__2023-08-31T23:09:08.895174+00:00 [queued]>
[2023-08-31T23:10:00.747+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.create_listings_raw_table manual__2023-08-31T23:09:08.895174+00:00 [queued]>
[2023-08-31T23:10:00.748+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-08-31T23:10:00.761+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryCreateEmptyTableOperator): create_listings_raw_table> on 2023-08-31 23:09:08.895174+00:00
[2023-08-31T23:10:00.766+0000] {standard_task_runner.py:57} INFO - Started process 415 to run task
[2023-08-31T23:10:00.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'create_listings_raw_table', 'manual__2023-08-31T23:09:08.895174+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp627wqh88']
[2023-08-31T23:10:00.772+0000] {standard_task_runner.py:85} INFO - Job 113: Subtask create_listings_raw_table
[2023-08-31T23:10:00.816+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509
[2023-08-31T23:10:00.816+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-08-31T23:09:08.895174+00:00/task_id=create_listings_raw_table'
[2023-08-31T23:10:00.819+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.create_listings_raw_table manual__2023-08-31T23:09:08.895174+00:00 [running]> on host 1a0e8b05e04d
[2023-08-31T23:10:00.901+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='create_listings_raw_table' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T23:09:08.895174+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T23:09:08.895174+00:00'
[2023-08-31T23:10:00.914+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-08-31T23:10:00.918+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-08-31T23:10:00.919+0000] {bigquery.py:1507} INFO - Creating table
[2023-08-31T23:10:02.341+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1508, in execute
    table = bq_hook.create_empty_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 420, in create_empty_table
    return self.get_client(project_id=project_id, location=location).create_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 782, in create_table
    api_response = self._call_api(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 816, in _call_api
    return call()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func
    return retry_target(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/retry.py", line 191, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/_http/__init__.py", line 494, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.BadRequest: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/autotrader-toyota-dashboard/datasets/autotrader-toyota-dashboard.autotrader_staging/tables?prettyPrint=false: Invalid dataset ID "autotrader-toyota-dashboard.autotrader_staging". Dataset IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long.
[2023-08-31T23:10:02.356+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Autotrader_ETL_DAG, task_id=create_listings_raw_table, execution_date=20230831T230908, start_date=20230831T231000, end_date=20230831T231002
[2023-08-31T23:10:02.368+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 113 for task create_listings_raw_table (400 POST https://bigquery.googleapis.com/bigquery/v2/projects/autotrader-toyota-dashboard/datasets/autotrader-toyota-dashboard.autotrader_staging/tables?prettyPrint=false: Invalid dataset ID "autotrader-toyota-dashboard.autotrader_staging". Dataset IDs must be alphanumeric (plus underscores) and must be at most 1024 characters long.; 415)
[2023-08-31T23:10:02.389+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-31T23:10:02.413+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
