[2023-12-03T01:31:22.182+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509
[2023-12-03T01:31:22.183+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings'
[2023-12-03T01:31:22.218+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509
[2023-12-03T01:31:22.219+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings'
[2023-12-03T01:31:22.245+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T01:31:20.093983+00:00 [queued]>
[2023-12-03T01:31:22.253+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T01:31:20.093983+00:00 [queued]>
[2023-12-03T01:31:22.254+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-03T01:31:22.270+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_listings> on 2023-12-03 01:31:20.093983+00:00
[2023-12-03T01:31:22.276+0000] {standard_task_runner.py:57} INFO - Started process 1082 to run task
[2023-12-03T01:31:22.279+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'extract_listings', 'manual__2023-12-03T01:31:20.093983+00:00', '--job-id', '1392', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmpidpv_id5']
[2023-12-03T01:31:22.281+0000] {standard_task_runner.py:85} INFO - Job 1392: Subtask extract_listings
[2023-12-03T01:31:22.322+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509
[2023-12-03T01:31:22.323+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-12-03T01:31:20.093983+00:00/task_id=extract_listings'
[2023-12-03T01:31:22.325+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.extract_listings manual__2023-12-03T01:31:20.093983+00:00 [running]> on host 172bfe53c091
[2023-12-03T01:31:22.410+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='extract_listings' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T01:31:20.093983+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T01:31:20.093983+00:00'
[2023-12-03T01:31:24.668+0000] {logging_mixin.py:151} INFO - <Element html at 0x7fb752280860>
[2023-12-03T01:31:24.671+0000] {logging_mixin.py:151} INFO - []
[2023-12-03T01:31:24.690+0000] {python.py:194} INFO - Done. Returned value was: list index out of range
[2023-12-03T01:31:24.698+0000] {xcom.py:661} ERROR - Object of type IndexError is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-03T01:31:24.700+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'IndexError'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2485, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IndexError is not JSON serializable
[2023-12-03T01:31:24.709+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=extract_listings, execution_date=20231203T013120, start_date=20231203T013122, end_date=20231203T013124
[2023-12-03T01:31:24.721+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1392 for task extract_listings (Object of type IndexError is not JSON serializable; 1082)
[2023-12-03T01:31:24.743+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-03T01:31:24.767+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
