[2023-09-03T09:34:26.574+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509
[2023-09-03T09:34:26.575+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim'
[2023-09-03T09:34:26.614+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509
[2023-09-03T09:34:26.615+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim'
[2023-09-03T09:34:26.655+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.create_car_dim manual__2023-09-03T09:33:41.816579+00:00 [queued]>
[2023-09-03T09:34:26.670+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Autotrader_ETL_DAG.create_car_dim manual__2023-09-03T09:33:41.816579+00:00 [queued]>
[2023-09-03T09:34:26.670+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-09-03T09:34:26.697+0000] {taskinstance.py:1382} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_car_dim> on 2023-09-03 09:33:41.816579+00:00
[2023-09-03T09:34:26.709+0000] {standard_task_runner.py:57} INFO - Started process 4287 to run task
[2023-09-03T09:34:26.712+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Autotrader_ETL_DAG', 'create_car_dim', 'manual__2023-09-03T09:33:41.816579+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/autotrader_etl.py', '--cfg-path', '/tmp/tmp8zsrir6_']
[2023-09-03T09:34:26.715+0000] {standard_task_runner.py:85} INFO - Job 277: Subtask create_car_dim
[2023-09-03T09:34:26.767+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509
[2023-09-03T09:34:26.768+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=Autotrader_ETL_DAG/run_id=manual__2023-09-03T09:33:41.816579+00:00/task_id=create_car_dim'
[2023-09-03T09:34:26.771+0000] {task_command.py:415} INFO - Running <TaskInstance: Autotrader_ETL_DAG.create_car_dim manual__2023-09-03T09:33:41.816579+00:00 [running]> on host 1a0e8b05e04d
[2023-09-03T09:34:26.871+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Autotrader_ETL_DAG' AIRFLOW_CTX_TASK_ID='create_car_dim' AIRFLOW_CTX_EXECUTION_DATE='2023-09-03T09:33:41.816579+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-03T09:33:41.816579+00:00'
[2023-09-03T09:34:26.875+0000] {bigquery.py:1234} INFO - Executing: CREATE TABLE
        autotrader-toyota-dashboard.autotrader_transformed.car_dim 
        (
        car_key INT64 NOT NULL,
        year INT64,
        model STRING,
        type STRING,
        PRIMARY KEY (car_key) NOT ENFORCED
        );
[2023-09-03T09:34:26.885+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-09-03T09:34:26.890+0000] {base.py:73} INFO - Using connection ID 'google_cloud' for task execution.
[2023-09-03T09:34:26.896+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/providers/google/cloud/hooks/bigquery.py:2109 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2023-09-03T09:34:26.942+0000] {bigquery.py:1596} INFO - Inserting job ***_1693733666941427_3a85a2d2a598f6057b6f558a88fc136b
[2023-09-03T09:34:28.390+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1242, in execute
    self.job_id = self.hook.run_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2244, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 467, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1602, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1520, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1510, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Conflict: 409 Already Exists: Table autotrader-toyota-dashboard:autotrader_transformed.car_dim

Location: asia-southeast1
Job ID: airflow_1693733666941427_3a85a2d2a598f6057b6f558a88fc136b

[2023-09-03T09:34:28.404+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=Autotrader_ETL_DAG, task_id=create_car_dim, execution_date=20230903T093341, start_date=20230903T093426, end_date=20230903T093428
[2023-09-03T09:34:28.430+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 277 for task create_car_dim (409 Already Exists: Table autotrader-toyota-dashboard:autotrader_transformed.car_dim

Location: asia-southeast1
Job ID: airflow_1693733666941427_3a85a2d2a598f6057b6f558a88fc136b
; 4287)
[2023-09-03T09:34:28.452+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-03T09:34:28.482+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
